### ISSUE TITLE
Windows cannot find the file specified Traceback Please resolve

### ISSUE THREAD

**Issue by knightsun** [OlympicCode/vHackAPI-Python#24]
Traceback (most recent call last):
  File "F:\vhack\main.py", line 78, in <module>
    r = run()
  File "F:\vhack\main.py", line 37, in __init__
    self.init()
  File "F:\vhack\main.py", line 76, in init
    self.c.attack(self)
  File "F:\vhack\console.py", line 473, in attack
    data = self.getIP(True, obj.maxanti_normal, obj.mode, obj.active_cluster_protection)
  File "F:\vhack\console.py", line 226, in getIP
    result, ip = wait_for.result()
  File "C:\Python27\lib\site-packages\concurrent\futures\_base.py", line 429, in result
    return self.__get_result()
  File "C:\Python27\lib\site-packages\concurrent\futures\thread.py", line 62, in run
    result = self.fn(*self.args, **self.kwargs)
  File "F:\vhack\console.py", line 138, in calc_img
    image) or "Watched by the FBI" in pytesseract.image_to_string(image):
  File "C:\Python27\lib\site-packages\pytesseract\pytesseract.py", line 122, in image_to_string
    config=config)
  File "C:\Python27\lib\site-packages\pytesseract\pytesseract.py", line 46, in run_tesseract
    proc = subprocess.Popen(command, stderr=subprocess.PIPE)
  File "C:\Python27\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

**Comment by itsfolf** [comment]
Please install all the dependencies

**Comment by knightsun** [comment]
i already installed all Pillow, Tesseract, requests,pytesseract, futures, Beautifulsoup4

 i am getting this error after line:
  Packing IP list 6

**Comment by knightsun** [comment]
best list for tournament :
DDoS not ready. 3h, 50m left.
Blocked, trying again. Delaying 0 seconds
Blocked, trying again. Delaying 0 seconds
Packing IP list 6

Traceback (most recent call last):
  File "F:\vhack\main.py", line 78, in <module>
    r = run()
  File "F:\vhack\main.py", line 37, in __init__
    self.init()
  File "F:\vhack\main.py", line 76, in init
    self.c.attack(self)
  File "F:\vhack\console.py", line 473, in attack
    data = self.getIP(True, obj.maxanti_normal, obj.mode, obj.active_cluster_protection)
  File "F:\vhack\console.py", line 226, in getIP
    result, ip = wait_for.result()
  File "C:\Python27\lib\site-packages\concurrent\futures\_base.py", line 429, in result
    return self.__get_result()
  File "C:\Python27\lib\site-packages\concurrent\futures\thread.py", line 62, in run
    result = self.fn(*self.args, **self.kwargs)
  File "F:\vhack\console.py", line 138, in calc_img
    image) or "Watched by the FBI" in pytesseract.image_to_string(image):
  File "C:\Python27\lib\site-packages\pytesseract\pytesseract.py", line 122, in image_to_string
    config=config)
  File "C:\Python27\lib\site-packages\pytesseract\pytesseract.py", line 46, in run_tesseract
    proc = subprocess.Popen(command, stderr=subprocess.PIPE)
  File "C:\Python27\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
>>>

**Comment by wookienz** [comment]
Not a windows user, however:
Is pytesseract and subprocess installed?

**Comment by knightsun** [comment]
yes i have installed both

**Comment by wookienz** [comment]
concurrent.futures installed?

**Comment by knightsun** [comment]
i have installed futures

**Comment by wookienz** [comment]
sorry cant help more.
As long as you have installed dependencies using pip and the requirements file switch it should work.
I dont maintain Windows version so cant help.

**Comment by vBlackOut** [comment]
hello :) i'm back you use ? the executable ? main.exe ?
on the windows/main.exe
