### ISSUE TITLE
No modul named urllib2

### ISSUE THREAD

**Issue by Heacien** [OlympicCode/vHackAPI-Python#35]
`/data/user/0/org.qpython.qpy3/files/bin/qpython-android5.sh "/storage/emulated/0/qpython/projects3/vHackXTBot-Python-master/main.py" && exit
TBot-Python-master/main.py" && exit      <
Traceback (most recent call last):
  File "/storage/emulated/0/qpython/projects3/vHackXTBot-Python-master/main.py", line 4, in <module>
    from console import Console
  File "/storage/emulated/0/qpython/projects3/vHackXTBot-Python-master/console.py", line 5, in <module>
    from utils import Utils
  File "/storage/emulated/0/qpython/projects3/vHackXTBot-Python-master/utils.py", line 7, in <module>
    import urllib2
ImportError: No module named urllib2`

May im total dumb, but the script cnt find urllib2 on android :/h

**Comment by vBlackOut** [comment]
weird ! 
python2 -m pip install urllib2 
for install library on your device

**Comment by vBlackOut** [comment]
close no reponse
