### ISSUE TITLE
Bot not starting

### ISSUE THREAD

**Issue by ghost** [OlympicCode/vHackAPI-Python#38]
/home/vHackXTBot# ./main.py
Traceback (most recent call last):
  File "./main.py", line 146, in <module>
    r = run()
  File "./main.py", line 43, in __init__
    self.b = Botnet(self.player)
  File "/home/vHackXTBot/botnet.py", line 21, in __init__
    self._initbot()
  File "/home/vHackXTBot/botnet.py", line 34, in _initbot
    bot = Bot(i['bID'], i['bLVL'], i['bPRICE'], self.username, self.password, self.uhash)
KeyError: 'bID'

**Comment by vBlackOut** [comment]
you are connected on discord ?

**Comment by vBlackOut** [comment]
i closed, but i disabled functionality wait for update bot.
