### ISSUE TITLE
Bot still not working

### ISSUE THREAD

**Issue by ghost** [OlympicCode/vHackAPI-Python#39]
Traceback (most recent call last):
  File "./main.py", line 147, in <module>
    r = run()
  File "./main.py", line 47, in __init__
    self.init()
  File "./main.py", line 105, in init
    number_botnet = json.loads(self.b._botnetInfo())
AttributeError: run instance has no attribute 'b'

**Comment by vBlackOut** [comment]
work now ? redownload please

**Comment by ghost** [comment]
working now

**Comment by vBlackOut** [comment]
Great :) i close issue
