### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by kendertas** [OlympicCode/vHackAPI-Python#4]
Hello, installed all requirements, but I get this error

> ** Force Mode to 'Potator' for Tournament **
Packing IP list 6
Traceback (most recent call last):
  File "main.py", line 139, in <module>
    c.attack(attacks_tournament, maxanti_tournament, wait, mode, api)
  File "/home/kender/Programs/vHackAPI-Python/console.py", line 374, in attack
    data = self.getIP(True, max, mode, api)
  File "/home/kender/Programs/vHackAPI-Python/console.py", line 168, in getIP
    result, ip = wait_for.result()
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/kender/Programs/vHackAPI-Python/console.py", line 95, in calc_img
    if "Hatched by the FBI" in pytesseract.image_to_string(image) or "Watched by the FBI" in pytesseract.image_to_string(image):
  File "/usr/local/lib/python2.7/dist-packages/pytesseract/pytesseract.py", line 161, in image_to_string
    config=config)
  File "/usr/local/lib/python2.7/dist-packages/pytesseract/pytesseract.py", line 94, in run_tesseract
    stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by kendertas** [comment]
[update]
tried to use virtualenv, installed all requirements, but still get same error.

**Comment by ghost** [comment]
u need: apt-get install tesseract-ocr to fix this "issue"

**Comment by kendertas** [comment]
It worked, problem fixed.
Thank you
