### ISSUE TITLE
Traceback Error

### ISSUE THREAD

**Issue by FloloKrypton** [OlympicCode/vHackAPI-Python#40]
Traceback (most recent call last):
  File "./main.py", line 132, in <module>
    r = run()
  File "./main.py", line 39, in __init__
    self.init()
  File "./main.py", line 128, in init
    self.c.attack(self)
  File "/root/vHackXTBot-Python-add-license-1/console.py", line 469, in attack
    self.getIP(True, obj.maxanti_normal, obj.mode, obj.active_cluster_protection)
  File "/root/vHackXTBot-Python-add-license-1/console.py", line 230, in getIP
    result, ip = wait_for.result()
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 429, in result
    return self.__get_result()
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/thread.py", line 62, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/vHackXTBot-Python-add-license-1/console.py", line 169, in calc_img
    result = self.attackIP(jsons['ipaddress'], mode)
  File "/root/vHackXTBot-Python-add-license-1/console.py", line 436, in attackIP
    ipsplevel) + "&FW=" + str(fwlevel) + "&AV=" + str(avlevel))
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='vhack.olympiccode.ga', port=443): Max retries exceeded with url: /database/submit.php?IP=78.231.4.40&USR=???&MONEY=???&IPSP=4160&FW=4272&AV=4444 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8f48995450>: Failed to establish a new connection: [Errno 110] Connection timed out',))

**Comment by vBlackOut** [comment]
please redownload the projet, your version not last version.

**Comment by FloloKrypton** [comment]
It is latest. Downloaded 10 minutes ago

**Comment by vBlackOut** [comment]
weird the send server OlympicCode is disabled ...

**Comment by vBlackOut** [comment]
vHackXTBot-Python-add-license-1 is not on OlympicCode project is old version.

**Comment by vBlackOut** [comment]
test : 
git clone https://github.com/OlympicCode/vHackXTBot-Python
cd vHackXTBot-Python
python main.py

**Comment by vBlackOut** [comment]
vHackXTBot-Python-add-license-1 project updated close the issue
