### ISSUE TITLE
Traceback Error

### ISSUE THREAD

**Issue by HaRo0** [OlympicCode/vHackAPI-Python#43]
Traceback (most recent call last):
  File "B:\vHackXTBot-Python-master\main.py", line 154, in <module>
    r = run()
  File "B:\vHackXTBot-Python-master\main.py", line 46, in __init__
    self.init()
  File "B:\vHackXTBot-Python-master\main.py", line 104, in init
    self.b.upgradebotnet(i['hostname'], int(i['running']), count)
  File "B:\vHackXTBot-Python-master\botnet.py", line 108, in upgradebotnet
    new_bal = self.upgradesinglebot(hostname, ofwhat)
  File "B:\vHackXTBot-Python-master\botnet.py", line 147, in upgradesinglebot
    jsons = json.loads(response)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 1160 - line 1 column 1161 (char 1159 - 1160)

**Comment by vBlackOut** [comment]
you use lastest version ?

**Comment by HaRo0** [comment]
Yes

**Comment by vBlackOut** [comment]
i close for resolve to Teamviewers
