### ISSUE TITLE
Botnet Bug

### ISSUE THREAD

**Issue by AtjonTV** [OlympicCode/vHackAPI-Python#51]
System
```
Raspbian 9 GNU/Linux
Python 2.x
```

Traceback
```
Traceback (most recent call last):
  File "/home/pi/vhack-bot/main.py", line 160, in <module>
    r = run()
  File "/home/pi/vhack-bot/main.py", line 48, in init
    self.init()
  File "/home/pi/vhack-bot/main.py", line 105, in init
    self.b.upgradebotnet(i['hostname'], int(i['running']), count)
  File "/home/pi/vhack-bot/botnet.py", line 133, in upgradebotnet
    if int(get_infobot['data'][count][unicode(self.ofwhat[i-remove])]) == int(maxofwhat):
IndexError: list index out of range
```

Info
`I will fix that bug as soon as I'm at home .. I know how to fix it!
`

**Comment by AtjonTV** [comment]
I made changes but can't confirm the but as fixed.

As soon as the changes are confirmed to fix the issue, I'll create a pull request.

**Comment by AtjonTV** [comment]
This bug is unfixable, it occurres if a user combines botnet PC's while the vHackXTBot is making botnet updates.

Only solution I found is:
* stop the bot
* combine PC's
* start the bot
