### ISSUE TITLE
windows problem

### ISSUE THREAD

**Issue by ALENBERG1** [OlympicCode/vHackAPI-Python#7]
when i enter the username and the password it write:

"Traceback (most recent call last):
    File "main.py", line 159 in <module>
    File "json\__init___.pyc", line 339, in loads
    File "json\decoder.pyc", line 364, in decode
    File "json\decoder.pyc", line 382, in raw_decode
ValueError: No JSON object could be decoded

**Comment by vBlackOut** [comment]
look the last update
