### ISSUE TITLE
linux error

### ISSUE THREAD

**Issue by knightsun** [OlympicCode/vHackAPI-Python#9]
Traceback (most recent call last):
  File "main.py", line 110, in <module>
    jsons = json.loads(u.getTasks())
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by vBlackOut** [comment]
i'm refix the problem check

**Comment by knightsun** [comment]
thanks a lot solved you are a savior
